apiVersion: v1
kind: Service
metadata:
  name: books-service-svc
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: books-service
  ports:
    - targetPort: 8000
      port: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-deploy
  annotations:
    kubernetes.io/change-cause: version 'v1'
  labels:
    app: books-service
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: books-service
  template:
    metadata:
      labels:
        app: books-service
    spec:
      containers:
        - name: books
          image: shaikkhajaibrahim/libbookssvc:1.0
          envFrom:
            - secretRef:
                name: books-svc-secrets
          startupProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /docs
              port: 8000
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            exec:
              command:
                - /bin/sh
                - -c
                - ps aux | grep "uvicorn"
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            tcpSocket:
              port: 8000
          resources:
            requests:
              cpu: 68m
              memory: 100Mi
            limits:
              cpu: 128m
              memory: 200Mi
          ports:
            - name: books-port
              containerPort: 8000
        
