apiVersion: v1
kind: Secret
metadata:
  name: users-db-secrets
data:
  POSTGRES_USER: dXNlcg==
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_DB: dXNlcnNkYg==
---
apiVersion: v1
kind: Secret
metadata:
  name: books-db-secrets
data:
  POSTGRES_USER: dXNlcg==
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_DB: Ym9va3NkYg==
---
apiVersion: v1
kind: Secret
metadata:
  name: users-svc-secrets
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAdXNlcnMtZGItc3ZjOjU0MzIvdXNlcnNkYg==
  SECRET_KEY: WXRERVZXbkwzNWFBSVAtNXl4ZUxqQVo0OVI5MjAtbU1ORGZ3UHlXVUx1NjNIRnNZem8wZi1MTzJJbnhDOGV1NDI4aw==
---
apiVersion: v1
kind: Secret
metadata:
  name: books-svc-secrets
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAYm9va3MtZGItc3ZjOjU0MzIvYm9va3NkYg==
  SECRET_KEY: WXRERVZXbkwzNWFBSVAtNXl4ZUxqQVo0OVI5MjAtbU1ORGZ3UHlXVUx1NjNIRnNZem8wZi1MTzJJbnhDOGV1NDI4aw==
---
apiVersion: v1
kind: Secret
metadata:
  name: library-secrets
data:
  REACT_APP_BACKEND_API_URL: aHR0cDovL3VzZXJzLXNlcnZpY2Utc3ZjOjgwMDAvYXBpL3Yx
  REACT_APP_BOOKS_API_URL: aHR0cDovL2Jvb2tzLXNlcnZpY2Utc3ZjOjgwMDAvYXBpL3YxL2Jvb2tz
  REACT_APP_USERS_API_URL: aHR0cDovL3VzZXJzLXNlcnZpY2Utc3ZjOjgwMDAvYXBpL3YxL3VzZXJz