apiVersion: v1
kind: Service
metadata:
  name: users-db-svc
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    db: users
  ports:
    - targetPort: 5432
      port: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: users-db-sts
  labels:
    db: users
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      db: users
  serviceName: users-db-svc
  template:
    metadata:
      labels:
        db: users
    spec:
      containers:
        - name: users-db
          image: postgres:15-alpine
          envFrom:
              - secretRef:
                  name: users-db-secrets
          startupProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            tcpSocket:
              port: 5432
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            exec:
              command:
                - /bin/sh
                - -c
                - ps aux | grep "postgres"
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            tcpSocket:
              port: 5432
          resources:
            requests:
              cpu: 68m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 250Mi
          ports:
            - containerPort: 5432
              name: usersdb-port
          volumeMounts:
            - name: users-db-vol
              mountPath: /var/lib/postgresql/data
              subPath: data
  volumeClaimTemplates:
    - metadata:
        name: users-db-vol
        labels:
          db: users
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "1Gi"
        storageClassName: standard-rwo
